// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB44rzprsmw_spoKHyjgk4-ea7iNi7lV9I',
    appId: '1:456602364782:web:54162687fb32ea0dc9af7f',
    messagingSenderId: '456602364782',
    projectId: 'rheumatology-4f669',
    authDomain: 'rheumatology-4f669.firebaseapp.com',
    storageBucket: 'rheumatology-4f669.firebasestorage.app',
    measurementId: 'G-92XZWNQ6VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHxNosmundwuzxNiZV0cxX_OdAmaqqlQ',
    appId: '1:456602364782:android:3fc7c7edbc780b5bc9af7f',
    messagingSenderId: '456602364782',
    projectId: 'rheumatology-4f669',
    storageBucket: 'rheumatology-4f669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0v_SsjqZQj1sf8vNlQRwiX5K-jrLXuk',
    appId: '1:456602364782:ios:e0585d23a9b42f6dc9af7f',
    messagingSenderId: '456602364782',
    projectId: 'rheumatology-4f669',
    storageBucket: 'rheumatology-4f669.firebasestorage.app',
    androidClientId: '456602364782-r60ql59cqfhast6dgih3flg9su4eun8n.apps.googleusercontent.com',
    iosClientId: '456602364782-81kcri4v16s8fhpd2eqg027drdg6s5nb.apps.googleusercontent.com',
    iosBundleId: 'com.rhumato.oran.congres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx0v_SsjqZQj1sf8vNlQRwiX5K-jrLXuk',
    appId: '1:456602364782:ios:e0585d23a9b42f6dc9af7f',
    messagingSenderId: '456602364782',
    projectId: 'rheumatology-4f669',
    storageBucket: 'rheumatology-4f669.firebasestorage.app',
    androidClientId: '456602364782-r60ql59cqfhast6dgih3flg9su4eun8n.apps.googleusercontent.com',
    iosClientId: '456602364782-81kcri4v16s8fhpd2eqg027drdg6s5nb.apps.googleusercontent.com',
    iosBundleId: 'com.rhumato.oran.congres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB44rzprsmw_spoKHyjgk4-ea7iNi7lV9I',
    appId: '1:456602364782:web:048ea312df0a6751c9af7f',
    messagingSenderId: '456602364782',
    projectId: 'rheumatology-4f669',
    authDomain: 'rheumatology-4f669.firebaseapp.com',
    storageBucket: 'rheumatology-4f669.firebasestorage.app',
    measurementId: 'G-688VLWJ592',
  );

}